Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoEstoque.Models
{
    public class Categoria
    {
        public int CategoriaId { get; set; }
        public string Nome { get; set; }
        public ICollection<Produto> Produtos { get; set; }
               
    }
}

Models/Contexto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GestaoEstoque.Mapeamentos;
using Microsoft.EntityFrameworkCore;

namespace GestaoEstoque.Models
{
    public class Contexto : DbContext
    {
        public DbSet<Produto> Produtos { get; set; }
        public DbSet<Movimentacao> Movimentacacoes { get; set; }
        public DbSet<Categoria> Categorias { get; set; }

        public Contexto(DbContextOptions<Contexto> options) : base(options)
        { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfiguration(new ProdutoMap());
            modelBuilder.ApplyConfiguration(new MovimentacaoMap());
            modelBuilder.ApplyConfiguration(new CategoriaMap());

        }
    }
}

Models/ErrorViewModel.cs
namespace GestaoEstoque.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Movimentacao.cs
namespace GestaoEstoque.Models
{
    public class Movimentacao
    {
        public int MovimrntacaoId { get; set; }
        public int ProdutoId { get; set; }
        public Produto Produto { get; set; }
        public string Descricao { get; set; }
        public string DataMovimentacao { get; set; }

    

    }
}

Models/Produto.cs
namespace GestaoEstoque.Models
{
    public class Produto
    {
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public int Quantidade { get; set; }
        public double Preco { get; set; }
        public int CategoriaId { get; set; }

        //Propriedade de navegação
        public Categoria Categoria { get; set; }
        public ICollection<Movimentacao> Movimentacoes { get; set; }


    }
}

Controllers/CategoriaController.cs
using GestaoEstoque.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GestaoEstoque.Controllers
{
    [Route("[controller]")]
    public class CategoriaController : Controller
    {
        private readonly Contexto _contexto;

        public CategoriaController(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _contexto.Categorias.ToListAsync());
        }

        [HttpGet]
        public IActionResult NovaCategoria()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NovaCategoria(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                await _contexto.Categorias.AddAsync(categoria);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);

        }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GestaoEstoque.Models;

namespace GestaoEstoque.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Categoria/Index.cshtml
@model IEnumerable<Categoria>

@{
    ViewData["Title"] = "Categorias Registradas";

    <div class="container p-5">
        <div class="border border-light rounded p-5">
            <a asp-controller="Categoria" asp-action="NovaCategoria" class="btn btn-sm btn-outline-info">
                Nova Categoria
            </a>
        </div>

        <hr />

        <table class="table table-striped table-hover table-sm">
            <thead>
                <tr class="thead-light">
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        Ações
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem=> item.Nome)
                        </td>
                        <td>
                            <div class="row">
                                <a asp-controller="Categoria" asp-action="AtualizarCategoria" asp-route-categoriaId="@item.CategoriaId" class="btn btn-sm btn-outline-primary rounded-circle">
                                    <i class="fa fa-pencil-square-o"></i>
                                </a>
                                <form asp-controller"Categoria" asp-action="ExcluirCategoria" asp-route-categoriaId="@item.CategoriaId">
                                    <button type="submit" class="btn btn-sm btn-outline-danger rounded-circle">
                                        <i class="fa fa-pencil-times-circle"></i>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

}

Views/Categoria/NovaCategoria.cshtml
@model Categoria

@{
     ViewData["Title"] = "Nova Categoria";

     <div class="container p-5">
        <div class="row">
            <div class="col-6 border border-light rounded p-5 shadow">
                <h1>Categorias</h1>
            </div>
        </div>
     </div>


}


@* https://www.youtube.com/watch?v=kP0XR0mRJ0w  14:37*@

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestao Estoque</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="https://bootswatch.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestaoEstoque.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestao Estoque</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Gestao Estoque - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>